### ISSUE TITLE
Cannot build the project due to GameNetworkingSockets issue

### ISSUE THREAD

**Issue by Eager31** [tiltedphoques/CyberpunkMP#53]
1. Navigate to the repository using a command prompt.
2. Check out the correct branch/tag if you're not working against main
3. Run `git submodule update --init` to pull in vendored dependencies
4. Run `xmake -y` (add `-v` for verbose output)

-> When running step 4 : 

````
[0m[1;38;5;1;1merror: [0msteamnetworkingsockets_connections.cpp
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp(1298): error C2039: 'c_str' n'est pas membre de 'std::basic_string_view<char,std::char_traits<char>>'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\__msvc_string_view.hpp(1341): note: voir la d�claration de 'std::basic_string_view<char,std::char_traits<char>>'
````

I tried to pull GameNetworkingSocker and fix, then using it a local dependency but without success. It keeps trying to pull this dependency and there's this issue. Probably a C++ misconfiguration

**Comment by poirierlouis** [comment]
It's been a long time since I build the project.
Also make sure you are using the right version of Microsoft SDK like mentioned in README.

You might want to try https://github.com/tiltedphoques/CyberpunkMP/issues/23#issuecomment-2499322420...

**Comment by Eager31** [comment]
I'v installed a fresh ubuntu server to try to build it, but without success, An issue in the same lib, but with different kind...
```
[0m[1;38;2;255;0;0;1merror: [0msrc/steamnetworkingsockets/clientlib/../steamnetworkingsockets_internal.h:677:113: error: ‘using string_view = using string_view = class std::basic_string_view<char>’ {aka ‘class std::basic_string_view<char>’} has no member named ‘c_str’; did you mean ‘_M_str’?
  677 |                         AssertMsg2( false, "Failed to serialize identity to %s message.  %s", msg.GetTypeName().c_str(), identityToProtobufErrMsg ); \
      |                                                                                                                 ^~~~~
src/public/tier0/dbg.h:82:85: note: in definition of macro ‘_AssertMsgSmall’
   82 |                                 AssertMsgHelper< _bFatal, sizeof( DbgMsgCountArgsT( __VA_ARGS__ ) ) == 1 >::AssertFailed( __FILE__, __LINE__, __VA_ARGS__ ); \
      |                                                                                     ^~~~~~~~~~~
src/public/tier0/dbg.h:136:105: note: in expansion of macro ‘AssertMsg’
  136 | #define AssertMsg2( _exp, _msg, a1, a2 )                                                                AssertMsg( _exp, _msg, a1, a2 )
      |                                                                                                         ^~~~~~~~~
src/steamnetworkingsockets/clientlib/../steamnetworkingsockets_internal.h:677:25: note: in expansion of macro ‘AssertMsg2’
  677 |                         AssertMsg2( false, "Failed to serialize identity to %s message.  %s", msg.GetTypeName().c_str(), identityToProtobufErrMsg ); \
      |                         ^~~~~~~~~~
src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp:1298:9: note: in expansion of macro ‘SteamNetworkingIdentityToProtobuf’
 1298 |         SteamNetworkingIdentityToProtobuf( m_identityLocal, msgCert, identity_string, legacy_identity_binary, legacy_steam_id );
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/public/tier0/dbg.h:82:106: error: template argument 2 is invalid
   82 |                                 AssertMsgHelper< _bFatal, sizeof( DbgMsgCountArgsT( __VA_ARGS__ ) ) == 1 >::AssertFailed( __FILE__, __LINE__, __VA_ARGS__ ); \
  [38;2;255;255;0m> in [1msrc/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp[0m
```

Will try to reinstall a fresh windows with the SDK indicated, 
May I DM you on discord or smth ? I see you'r french 🇫‍🇷

**Comment by poirierlouis** [comment]
Well it should be working on Ubuntu Server too. I have one running and there is a configured Docker image which was tested.

> May I DM you on discord or smth ?

You can, but ultimately the best would be to ask in the dedicated sub-channel to share with everyone (also increase your odds to find a solution).

**Comment by Eager31** [comment]
I reinstalled a fresh windows. all the libs required. even the Microsoft SDK stated. still the same error when building : 
```
[0m[38;5;2;1m[  4%]:[0m compiling.proto.c++ src\common\steamnetworkingsockets_messages_certs.proto[0m
[0m[38;5;2;1m[  4%]:[0m compiling.proto.c++ src\common\steamnetworkingsockets_messages.proto[0m
[0m[38;5;2;1m[  4%]:[0m compiling.proto.c++ src\common\steamnetworkingsockets_messages_udp.proto[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\common\crypto_bcrypt.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\common\crypto_25519_donna.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\common\crypto.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\common\keypair.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\tier0\platformtime.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\common\steamid.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\common\crypto_textencode.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\vstdlib\strtools.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\tier0\dbg.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\tier1\netadr.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\tier1\utlmemory.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\steamnetworkingsockets\steamnetworkingsockets_certs.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\steamnetworkingsockets\steamnetworkingsockets_thinker.cpp[0m
[0m[38;5;2;1m[ 37%]:[0m compiling.release src\tier1\utlbuffer.cpp[0m
[0m[38;5;2;1m[ 39%]:[0m compiling.release src\steamnetworkingsockets\steamnetworkingsockets_certstore.cpp[0m
[0m[38;5;2;1m[ 41%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp[0m
[0m[38;5;2;1m[ 44%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_flat.cpp[0m
[0m[38;5;2;1m[ 46%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_lowlevel.cpp[0m
[0m[38;5;2;1m[ 48%]:[0m compiling.release src\steamnetworkingsockets\steamnetworkingsockets_shared.cpp[0m
[0m[38;5;2;1m[ 50%]:[0m compiling.release src\steamnetworkingsockets\steamnetworkingsockets_stats.cpp[0m
[0m[38;5;2;1m[ 53%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_snp.cpp[0m
[0m[38;5;2;1m[ 55%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_udp.cpp[0m
[0m[38;5;2;1m[ 57%]:[0m compiling.release src\steamnetworkingsockets\clientlib\csteamnetworkingmessages.cpp[0m
[0m[38;5;2;1m[ 60%]:[0m compiling.release src\steamnetworkingsockets\clientlib\csteamnetworkingsockets.cpp[0m
[0m[38;5;2;1m[ 62%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_p2p.cpp[0m
[0m[38;5;2;1m[ 64%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_stun.cpp[0m
[0m[38;5;2;1m[ 67%]:[0m compiling.release src\steamnetworkingsockets\clientlib\steamnetworkingsockets_p2p_ice.cpp[0m
[0m[38;5;2;1m[ 69%]:[0m compiling.release src\external\curve25519-donna\curve25519.c[0m
[0m[1;38;5;1;1merror: [0msteamnetworkingsockets_connections.cpp
src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp(1298): error C2039: 'c_str' n'est pas membre de 'std::basic_string_view<char,std::char_traits<char>>'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\__msvc_string_view.hpp(1341): note: voir la d�claration de 'std::basic_string_view<char,std::char_traits<char>>'

  [38;5;3m> in [1msrc\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp[0m
```

Would be glad if u reach me on discord. name's "_eager", 
Best regards Louis
